name: Generate ASCII Artwork

on: 
    push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        -   name: checkout Repo
            uses: actions/checkout@v4

        -   name: list Repo files
            run: ls -ltrha            

        -   name: Executing shell script
            run: ./ascii-script.sh

        -   name: list Repo files
            run: ls -ltrha

